= Rust configuration

== Automatic branch creation

By default, the Rust configuration does not automatically create branches (instead requiring users
to manually approve dependencies in the dependency dashboard).

To enable automatic branch creation, in your repository's `renovate.json`, extend from
`local>oxidecomputer/renovate-config//rust/autocreate` _after_ extending from the global preset.
This will enable:

- Automatic branch creation for dependencies
- Lockfile updates every Monday morning Pacific time

== Setting `rangeStrategy` to `bump`

Our configuration sets the https://docs.renovatebot.com/configuration-options/#rangestrategy[`rangeStrategy`] option to `bump`. This means that if a new version of a crate is released, the version in `Cargo.toml` is also bumped. This is generally desirable since new versions often have features or bugfixes that we'll start depending on--such that resolving to an older version would be a mistake. (But it's reasonable to disagree, in which case you can use the `update-lockfile` strategy.)

== Using `update-lockfile` for `x` or `x.y` dependencies

We currently use the `update-lockfile` strategy for dependencies specified as `x` or `x.y`. While the `bump` strategy also works for those dependencies, it will cause PRs for no-op updates (https://github.com/oxidecomputer/omicron/pull/5633[example]). We're choosing to not introduce that kind of churn.

== Groups

Renovate can be configured to update a group of crates together, via the `groupName` config. Currently, this is used for `rand`-related crates.

== Exclusions

The following crates are currently excluded from consideration:

- `vsss-rs`: Relatively delicate part of omicron (trust quorum), has shipped breakages in the past.
See https://github.com/oxidecomputer/renovate-config/issues/20[issue #20].
- `schemars`: We are on schemars 0.8 and expect to be on this version for the foreseeable future. Hence we disable major (to 1.0) and minor (to 0.9) updates.

NOTE: If you're excluding a new crate, be sure to add information about it to this section,
including the reason(s) for exclusion.
