= Rust configuration

== Automatic branch creation

By default, the Rust configuration does not automatically create branches (instead requiring users
to manually approve dependencies in the dependency dashboard).

To enable automatic branch creation, in your repository's `renovate.json`, extend from
`local>oxidecomputer/renovate-config//rust/autocreate` _after_ extending from the global preset.
This will enable:

- Automatic branch creation for dependencies
- Lockfile updates every Monday morning Pacific time

== Updating versions for `x` or `x.y` dependencies

Dependencies are often not fully specified as `x.y.z`, and instead specified as `x.y` or just a plain `x` (for crates at versions 1 or above). For example, dependencies can be specified as:

[source,toml]
```
[dependencies]
chrono = "0.4"
syn = "2" 
```

For these kinds of dependencies, Renovate will not update `Cargo.lock` versions at all if the corresponding `Cargo.toml` version doesn't need to be changed. This can lead to us being behind on crate versions.

To address this:

* Whenever versions are specified as `x` or `x.y` in `Cargo.toml` we use the https://docs.renovatebot.com/configuration-options/#rangestrategy[`update-lockfile` range strategy]. This causes `Cargo.lock` files for such dependencies to be updated.
* If a complete version `x.y.z` is specified, we want both the `Cargo.lock` and the `Cargo.toml` to be updated. For that, we fall back to the default `auto` strategy—which for Cargo is https://docs.renovatebot.com/modules/manager/cargo/#additional-information[almost always the same as `bump`]. (We don't want `update-lockfile` in these cases, because that won't touch `Cargo.toml`.)

The above logic is implemented via a `packageRules` entry in `crates.json` which matches version specifications against a regex.

It would be nice if Renovate could also change `Cargo.toml` files from `x.y` to `x.y.z` along with the `update-lockfile` strategy, but that doesn't appear to be supported in Renovate yet (as of 37.280.0).

== Exclusions

The following crates are currently excluded from consideration:

- `vsss-rs`: Relatively delicate part of omicron (trust quorum), has shipped breakages in the past.
See https://github.com/oxidecomputer/renovate-config/issues/20[issue #20].

NOTE: If you're excluding a new crate, be sure to add information about it to this section,
including the reason(s) for exclusion.
