name: Renovate

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level"
        required: true
        default: "INFO"
        type: choice
        options:
          - "TRACE"
          - "DEBUG"
          - "INFO"
          - "WARN"
          - "ERROR"
  schedule:
    - cron: "0/15 * * * *"

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    environment: prod
    env:
      LOG_LEVEL: ${{ github.event.inputs.log-level || 'INFO' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Create token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Self-hosted Renovate
        env:
          RENOVATE_TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: renovatebot/github-action@42c1d3cb1d1ca891765626ba71cdff5e757258de # v40.0.2
        with:
          configurationFile: runner/global.json
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
