name: Renovate Config Validate

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Validate preset files
        run: |
          npx --yes --package renovate -- renovate-config-validator --strict \
            *.json \
            actions/*.json \
            rust/*.json
          # TODO: Validate runner/global.json; unsupported by renovate-config-validator
          # Maybe a basic JSON Schema validation
